version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "4001:4001"

    volumes:
      - .:/app-backend
      - /app-backend/node_modules

    env_file:
      - .env
